{
    "current_observation":{
        "heat_index_c":"NA",
        "local_tz_long":"America/New_York",
        "observation_location":{
            "city":"Potomac, Potomac",
            "full":"Potomac, Potomac, Maryland",
            "elevation":"371 ft",
            "country":"US",
            "longitude":"-77.211441",
            "state":"Maryland",
            "country_iso3166":"US",
            "latitude":"39.024765"
        },
        "weather":"Scattered Clouds",
        "local_time_rfc822":"Tue, 19 Aug 2014 23:26:04 -0400",
        "forecast_url":"http://www.wunderground.com/US/MD/Potomac.html",
        "windchill_c":"NA",
        "estimated":{},
        "windchill_f":"NA",
        "pressure_in":"29.97",
        "dewpoint_string":"69 F (20 C)",
        "solarradiation":"0",
        "ob_url":"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=39.024765,-77.211441",
        "local_epoch":"1408505164",
        "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
        "display_location":{
            "city":"Potomac",
            "full":"Potomac, MD",
            "magic":"1",
            "state_name":"Maryland",
            "zip":"20854",
            "country":"US",
            "longitude":"-77.24093628",
            "state":"MD",
            "wmo":"99999",
            "country_iso3166":"US",
            "latitude":"39.02873993",
            "elevation":"82.00000000"
        },
        "precip_today_string":"0.00 in (0 mm)",
        "dewpoint_f":69,
        "dewpoint_c":20,
        "precip_today_metric":"0",
        "feelslike_c":"21.9",
        "image":{
            "url":"http://icons.wxug.com/graphics/wu2/logo_130x80.png",
            "link":"http://www.wunderground.com",
            "title":"Weather Underground"
        },
        "wind_mph":0.0,
        "wind_gust_kph":0,
        "feelslike_f":"71.4",
        "local_tz_short":"EDT",
        "precip_today_in":"0.00",
        "heat_index_f":"NA",
        "nowcast":"",
        "temp_f":71.4,
        "station_id":"KMDPOTOM5",
        "windchill_string":"NA",
        "temp_c":21.9,
        "visibility_km":"16.1",
        "pressure_trend":"+",
        "visibility_mi":"10.0",
        "wind_string":"Calm",
        "pressure_mb":"1015",
        "temperature_string":"71.4 F (21.9 C)",
        "wind_dir":"NNE",
        "icon":"partlycloudy",
        "wind_degrees":33,
        "precip_1hr_in":"0.00",
        "local_tz_offset":"-0400",
        "wind_kph":0,
        "wind_gust_mph":0,
        "observation_time":"Last Updated on August 19, 11:25 PM EDT",
        "UV":"0.0",
        "heat_index_string":"NA",
        "observation_epoch":"1408505141",
        "precip_1hr_metric":" 0",
        "relative_humidity":"91%",
        "observation_time_rfc822":"Tue, 19 Aug 2014 23:25:41 -0400",
        "precip_1hr_string":"0.00 in ( 0 mm)",
        "feelslike_string":"71.4 F (21.9 C)",
        "history_url":"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMDPOTOM5"
    },
    "response":{
        "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
        "version":"0.1",
        "features":{
            "conditions":1
        }
    }
}