{
    "hourly_forecast":[
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.92"
            },
            "temp":{
                "metric":"19",
                "english":"66"
            },
            "dewpoint":{
                "metric":"12",
                "english":"53"
            },
            "feelslike":{
                "metric":"19",
                "english":"66"
            },
            "wdir":{
                "degrees":"321",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"1",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"63",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"11:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"225",
                "weekday_name_night":"Thursday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"14",
                "weekday_name":"Thursday",
                "epoch":"1408071600",
                "month_name":"August",
                "pretty":"11:00 PM EDT on August 14, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Thursday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"23",
                "mon":"8",
                "weekday_name_unlang":"Thursday",
                "mday":"14",
                "hour":"23",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Thu"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1014",
                "english":"29.93"
            },
            "temp":{
                "metric":"18",
                "english":"64"
            },
            "dewpoint":{
                "metric":"11",
                "english":"52"
            },
            "feelslike":{
                "metric":"18",
                "english":"64"
            },
            "wdir":{
                "degrees":"321",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"65",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"12:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408075200",
                "month_name":"August",
                "pretty":"12:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"00",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"0",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1014",
                "english":"29.95"
            },
            "temp":{
                "metric":"17",
                "english":"62"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"17",
                "english":"62"
            },
            "wdir":{
                "degrees":"322",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"5",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"68",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"1:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408078800",
                "month_name":"August",
                "pretty":"1:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"01",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"1",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.96"
            },
            "temp":{
                "metric":"16",
                "english":"60"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"16",
                "english":"60"
            },
            "wdir":{
                "degrees":"325",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"72",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"2:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408082400",
                "month_name":"August",
                "pretty":"2:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"02",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"2",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.97"
            },
            "temp":{
                "metric":"15",
                "english":"59"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"15",
                "english":"59"
            },
            "wdir":{
                "degrees":"324",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"74",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"3:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408086000",
                "month_name":"August",
                "pretty":"3:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"03",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"3",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.97"
            },
            "temp":{
                "metric":"14",
                "english":"58"
            },
            "dewpoint":{
                "metric":"10",
                "english":"50"
            },
            "feelslike":{
                "metric":"14",
                "english":"58"
            },
            "wdir":{
                "degrees":"327",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"76",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"4:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408089600",
                "month_name":"August",
                "pretty":"4:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"04",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"4",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.97"
            },
            "temp":{
                "metric":"14",
                "english":"57"
            },
            "dewpoint":{
                "metric":"10",
                "english":"50"
            },
            "feelslike":{
                "metric":"14",
                "english":"57"
            },
            "wdir":{
                "degrees":"331",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"79",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"5:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408093200",
                "month_name":"August",
                "pretty":"5:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"05",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"5",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.98"
            },
            "temp":{
                "metric":"13",
                "english":"55"
            },
            "dewpoint":{
                "metric":"10",
                "english":"50"
            },
            "feelslike":{
                "metric":"13",
                "english":"55"
            },
            "wdir":{
                "degrees":"328",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"81",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"6:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408096800",
                "month_name":"August",
                "pretty":"6:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"06",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"6",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"29.99"
            },
            "temp":{
                "metric":"13",
                "english":"55"
            },
            "dewpoint":{
                "metric":"9",
                "english":"49"
            },
            "feelslike":{
                "metric":"13",
                "english":"55"
            },
            "wdir":{
                "degrees":"323",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"81",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"7:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408100400",
                "month_name":"August",
                "pretty":"7:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"07",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"7",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"30.01"
            },
            "temp":{
                "metric":"13",
                "english":"55"
            },
            "dewpoint":{
                "metric":"9",
                "english":"49"
            },
            "feelslike":{
                "metric":"13",
                "english":"55"
            },
            "wdir":{
                "degrees":"318",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"80",
            "uvi":"1",
            "pop":"0",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"8:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408104000",
                "month_name":"August",
                "pretty":"8:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"08",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"8",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"30.01"
            },
            "temp":{
                "metric":"14",
                "english":"58"
            },
            "dewpoint":{
                "metric":"10",
                "english":"50"
            },
            "feelslike":{
                "metric":"14",
                "english":"58"
            },
            "wdir":{
                "degrees":"312",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"75",
            "uvi":"2",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"9:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408107600",
                "month_name":"August",
                "pretty":"9:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"09",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"9",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1017",
                "english":"30.02"
            },
            "temp":{
                "metric":"16",
                "english":"61"
            },
            "dewpoint":{
                "metric":"10",
                "english":"50"
            },
            "feelslike":{
                "metric":"16",
                "english":"61"
            },
            "wdir":{
                "degrees":"307",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"66",
            "uvi":"4",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"10:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408111200",
                "month_name":"August",
                "pretty":"10:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"10",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"10",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1017",
                "english":"30.02"
            },
            "temp":{
                "metric":"18",
                "english":"65"
            },
            "dewpoint":{
                "metric":"9",
                "english":"49"
            },
            "feelslike":{
                "metric":"18",
                "english":"65"
            },
            "wdir":{
                "degrees":"305",
                "dir":"NW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"56",
            "uvi":"6",
            "pop":"0",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"11:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408114800",
                "month_name":"August",
                "pretty":"11:00 AM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"11",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"11",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"30.01"
            },
            "temp":{
                "metric":"20",
                "english":"68"
            },
            "dewpoint":{
                "metric":"9",
                "english":"48"
            },
            "feelslike":{
                "metric":"20",
                "english":"68"
            },
            "wdir":{
                "degrees":"302",
                "dir":"WNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"48",
            "uvi":"8",
            "pop":"0",
            "wspd":{
                "metric":"10",
                "english":"6"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"12:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408118400",
                "month_name":"August",
                "pretty":"12:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"12",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"12",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"30.01"
            },
            "temp":{
                "metric":"22",
                "english":"71"
            },
            "dewpoint":{
                "metric":"9",
                "english":"48"
            },
            "feelslike":{
                "metric":"22",
                "english":"71"
            },
            "wdir":{
                "degrees":"293",
                "dir":"WNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"43",
            "uvi":"9",
            "pop":"0",
            "wspd":{
                "metric":"10",
                "english":"6"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"1:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408122000",
                "month_name":"August",
                "pretty":"1:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"13",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"13",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"30.0"
            },
            "temp":{
                "metric":"23",
                "english":"74"
            },
            "dewpoint":{
                "metric":"9",
                "english":"48"
            },
            "feelslike":{
                "metric":"23",
                "english":"74"
            },
            "wdir":{
                "degrees":"284",
                "dir":"WNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"0",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"40",
            "uvi":"8",
            "pop":"0",
            "wspd":{
                "metric":"10",
                "english":"6"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"2:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408125600",
                "month_name":"August",
                "pretty":"2:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"14",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"14",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"29.99"
            },
            "temp":{
                "metric":"24",
                "english":"75"
            },
            "dewpoint":{
                "metric":"9",
                "english":"48"
            },
            "feelslike":{
                "metric":"24",
                "english":"75"
            },
            "wdir":{
                "degrees":"270",
                "dir":"W"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"1",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"38",
            "uvi":"7",
            "pop":"0",
            "wspd":{
                "metric":"11",
                "english":"7"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"3:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408129200",
                "month_name":"August",
                "pretty":"3:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"15",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"15",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.97"
            },
            "temp":{
                "metric":"25",
                "english":"77"
            },
            "dewpoint":{
                "metric":"9",
                "english":"48"
            },
            "feelslike":{
                "metric":"25",
                "english":"77"
            },
            "wdir":{
                "degrees":"271",
                "dir":"W"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"1",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"37",
            "uvi":"5",
            "pop":"0",
            "wspd":{
                "metric":"13",
                "english":"8"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"4:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408132800",
                "month_name":"August",
                "pretty":"4:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"16",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"16",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.96"
            },
            "temp":{
                "metric":"25",
                "english":"77"
            },
            "dewpoint":{
                "metric":"9",
                "english":"48"
            },
            "feelslike":{
                "metric":"25",
                "english":"77"
            },
            "wdir":{
                "degrees":"267",
                "dir":"W"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"3",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"36",
            "uvi":"3",
            "pop":"0",
            "wspd":{
                "metric":"13",
                "english":"8"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"5:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408136400",
                "month_name":"August",
                "pretty":"5:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"17",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"17",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1014",
                "english":"29.94"
            },
            "temp":{
                "metric":"25",
                "english":"77"
            },
            "dewpoint":{
                "metric":"9",
                "english":"49"
            },
            "feelslike":{
                "metric":"25",
                "english":"77"
            },
            "wdir":{
                "degrees":"266",
                "dir":"W"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"4",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"37",
            "uvi":"1",
            "pop":"0",
            "wspd":{
                "metric":"11",
                "english":"7"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"6:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408140000",
                "month_name":"August",
                "pretty":"6:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"18",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"18",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1014",
                "english":"29.94"
            },
            "temp":{
                "metric":"24",
                "english":"76"
            },
            "dewpoint":{
                "metric":"10",
                "english":"50"
            },
            "feelslike":{
                "metric":"24",
                "english":"76"
            },
            "wdir":{
                "degrees":"278",
                "dir":"W"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"8",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"40",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"10",
                "english":"6"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"7:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408143600",
                "month_name":"August",
                "pretty":"7:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"19",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"19",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1014",
                "english":"29.94"
            },
            "temp":{
                "metric":"23",
                "english":"73"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"23",
                "english":"73"
            },
            "wdir":{
                "degrees":"293",
                "dir":"WNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"10",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"46",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"8:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408147200",
                "month_name":"August",
                "pretty":"8:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"20",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"20",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1014",
                "english":"29.94"
            },
            "temp":{
                "metric":"21",
                "english":"69"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"21",
                "english":"69"
            },
            "wdir":{
                "degrees":"332",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"13",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"54",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"9:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408150800",
                "month_name":"August",
                "pretty":"9:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"21",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"21",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.96"
            },
            "temp":{
                "metric":"18",
                "english":"65"
            },
            "dewpoint":{
                "metric":"11",
                "english":"52"
            },
            "feelslike":{
                "metric":"18",
                "english":"65"
            },
            "wdir":{
                "degrees":"346",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"28",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Clear",
            "humidity":"64",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"10:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408154400",
                "month_name":"August",
                "pretty":"10:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"22",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"22",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.98"
            },
            "temp":{
                "metric":"17",
                "english":"62"
            },
            "dewpoint":{
                "metric":"12",
                "english":"53"
            },
            "feelslike":{
                "metric":"17",
                "english":"62"
            },
            "wdir":{
                "degrees":"351",
                "dir":"N"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"31",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"72",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"11:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"226",
                "weekday_name_night":"Friday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"15",
                "weekday_name":"Friday",
                "epoch":"1408158000",
                "month_name":"August",
                "pretty":"11:00 PM EDT on August 15, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Friday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"23",
                "mon":"8",
                "weekday_name_unlang":"Friday",
                "mday":"15",
                "hour":"23",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Fri"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"29.99"
            },
            "temp":{
                "metric":"16",
                "english":"61"
            },
            "dewpoint":{
                "metric":"12",
                "english":"53"
            },
            "feelslike":{
                "metric":"16",
                "english":"61"
            },
            "wdir":{
                "degrees":"349",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"39",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"74",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"12:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408161600",
                "month_name":"August",
                "pretty":"12:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"00",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"0",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"29.99"
            },
            "temp":{
                "metric":"16",
                "english":"60"
            },
            "dewpoint":{
                "metric":"11",
                "english":"52"
            },
            "feelslike":{
                "metric":"16",
                "english":"60"
            },
            "wdir":{
                "degrees":"347",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"33",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"76",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"1:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408165200",
                "month_name":"August",
                "pretty":"1:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"01",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"1",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"29.99"
            },
            "temp":{
                "metric":"16",
                "english":"60"
            },
            "dewpoint":{
                "metric":"11",
                "english":"52"
            },
            "feelslike":{
                "metric":"16",
                "english":"60"
            },
            "wdir":{
                "degrees":"347",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"43",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"76",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"2",
                "english":"1"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"2:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408168800",
                "month_name":"August",
                "pretty":"2:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"02",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"2",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"29.99"
            },
            "temp":{
                "metric":"15",
                "english":"59"
            },
            "dewpoint":{
                "metric":"11",
                "english":"52"
            },
            "feelslike":{
                "metric":"15",
                "english":"59"
            },
            "wdir":{
                "degrees":"341",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"38",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"78",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"2",
                "english":"1"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"3:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408172400",
                "month_name":"August",
                "pretty":"3:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"03",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"3",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.98"
            },
            "temp":{
                "metric":"14",
                "english":"58"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"14",
                "english":"58"
            },
            "wdir":{
                "degrees":"339",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"24",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Clear",
            "humidity":"78",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"4:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408176000",
                "month_name":"August",
                "pretty":"4:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"04",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"4",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.98"
            },
            "temp":{
                "metric":"14",
                "english":"57"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"14",
                "english":"57"
            },
            "wdir":{
                "degrees":"333",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"11",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"79",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"5:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408179600",
                "month_name":"August",
                "pretty":"5:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"05",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"5",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.98"
            },
            "temp":{
                "metric":"13",
                "english":"56"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"13",
                "english":"56"
            },
            "wdir":{
                "degrees":"327",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"3",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"82",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"6:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408183200",
                "month_name":"August",
                "pretty":"6:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"06",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"6",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1015",
                "english":"29.98"
            },
            "temp":{
                "metric":"13",
                "english":"56"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"13",
                "english":"56"
            },
            "wdir":{
                "degrees":"332",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"1",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"83",
            "uvi":"0",
            "pop":"0",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"7:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408186800",
                "month_name":"August",
                "pretty":"7:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"07",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"7",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"29.99"
            },
            "temp":{
                "metric":"13",
                "english":"56"
            },
            "dewpoint":{
                "metric":"11",
                "english":"51"
            },
            "feelslike":{
                "metric":"13",
                "english":"56"
            },
            "wdir":{
                "degrees":"335",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"1",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"83",
            "uvi":"1",
            "pop":"0",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"8:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408190400",
                "month_name":"August",
                "pretty":"8:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"08",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"8",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"30.0"
            },
            "temp":{
                "metric":"15",
                "english":"59"
            },
            "dewpoint":{
                "metric":"11",
                "english":"52"
            },
            "feelslike":{
                "metric":"15",
                "english":"59"
            },
            "wdir":{
                "degrees":"336",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"2",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"77",
            "uvi":"2",
            "pop":"0",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"9:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408194000",
                "month_name":"August",
                "pretty":"9:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"09",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"9",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1016",
                "english":"30.01"
            },
            "temp":{
                "metric":"18",
                "english":"64"
            },
            "dewpoint":{
                "metric":"12",
                "english":"53"
            },
            "feelslike":{
                "metric":"18",
                "english":"64"
            },
            "wdir":{
                "degrees":"330",
                "dir":"NNW"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"8",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Sunny",
            "humidity":"66",
            "uvi":"4",
            "pop":"0",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"10:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"227",
                "weekday_name_night":"Saturday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"16",
                "weekday_name":"Saturday",
                "epoch":"1408197600",
                "month_name":"August",
                "pretty":"10:00 AM EDT on August 16, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Saturday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"10",
                "mon":"8",
                "weekday_name_unlang":"Saturday",
                "mday":"16",
                "hour":"10",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Sat"
            },
            "condition":"Clear",
            "icon":"clear"
        }
    ],
    "response":{
        "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
        "version":"0.1",
        "features":{
            "hourly":1
        }
    }
}