{
    "current_observation":{
        "heat_index_c":"NA",
        "local_tz_long":"America/New_York",
        "observation_location":{
            "city":"Potomac, Potomac",
            "full":"Potomac, Potomac, Maryland",
            "elevation":"371 ft",
            "country":"US",
            "longitude":"-77.211441",
            "state":"Maryland",
            "country_iso3166":"US",
            "latitude":"39.024765"
        },
        "weather":"Mostly Cloudy",
        "local_time_rfc822":"Sun, 17 Aug 2014 22:46:07 -0400",
        "forecast_url":"http://www.wunderground.com/US/MD/Potomac.html",
        "windchill_c":"NA",
        "estimated":{},
        "windchill_f":"NA",
        "pressure_in":"29.98",
        "dewpoint_string":"70 F (21 C)",
        "solarradiation":"0",
        "ob_url":"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=39.024765,-77.211441",
        "local_epoch":"1408329967",
        "icon_url":"http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
        "display_location":{
            "city":"Potomac",
            "full":"Potomac, MD",
            "magic":"1",
            "state_name":"Maryland",
            "zip":"20854",
            "country":"US",
            "longitude":"-77.24093628",
            "state":"MD",
            "wmo":"99999",
            "country_iso3166":"US",
            "latitude":"39.02873993",
            "elevation":"82.00000000"
        },
        "precip_today_string":"0.00 in (0 mm)",
        "dewpoint_f":70,
        "dewpoint_c":21,
        "precip_today_metric":"0",
        "feelslike_c":"22.9",
        "image":{
            "url":"http://icons.wxug.com/graphics/wu2/logo_130x80.png",
            "link":"http://www.wunderground.com",
            "title":"Weather Underground"
        },
        "wind_mph":0.0,
        "wind_gust_kph":0,
        "feelslike_f":"73.3",
        "local_tz_short":"EDT",
        "precip_today_in":"0.00",
        "heat_index_f":"NA",
        "nowcast":"",
        "temp_f":73.3,
        "station_id":"KMDPOTOM5",
        "windchill_string":"NA",
        "temp_c":22.9,
        "visibility_km":"16.1",
        "pressure_trend":"+",
        "visibility_mi":"10.0",
        "wind_string":"Calm",
        "pressure_mb":"1015",
        "temperature_string":"73.3 F (22.9 C)",
        "wind_dir":"SW",
        "icon":"mostlycloudy",
        "wind_degrees":224,
        "precip_1hr_in":"0.00",
        "local_tz_offset":"-0400",
        "wind_kph":0,
        "wind_gust_mph":0,
        "observation_time":"Last Updated on August 17, 10:45 PM EDT",
        "UV":"0.0",
        "heat_index_string":"NA",
        "observation_epoch":"1408329947",
        "precip_1hr_metric":" 0",
        "relative_humidity":"91%",
        "observation_time_rfc822":"Sun, 17 Aug 2014 22:45:47 -0400",
        "precip_1hr_string":"0.00 in ( 0 mm)",
        "feelslike_string":"73.3 F (22.9 C)",
        "history_url":"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMDPOTOM5"
    },
    "response":{
        "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
        "version":"0.1",
        "features":{
            "conditions":1
        }
    }
}