{
    "hourly_forecast":[
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.9"
            },
            "temp":{
                "metric":"23",
                "english":"74"
            },
            "dewpoint":{
                "metric":"17",
                "english":"63"
            },
            "feelslike":{
                "metric":"23",
                "english":"74"
            },
            "wdir":{
                "degrees":"352",
                "dir":"N"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"8",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"70",
            "uvi":"0",
            "pop":"2",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"11:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"228",
                "weekday_name_night":"Sunday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"17",
                "weekday_name":"Sunday",
                "epoch":"1408330800",
                "month_name":"August",
                "pretty":"11:00 PM EDT on August 17, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Sunday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"23",
                "mon":"8",
                "weekday_name_unlang":"Sunday",
                "mday":"17",
                "hour":"23",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Sun"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.9"
            },
            "temp":{
                "metric":"22",
                "english":"72"
            },
            "dewpoint":{
                "metric":"17",
                "english":"63"
            },
            "feelslike":{
                "metric":"22",
                "english":"72"
            },
            "wdir":{
                "degrees":"5",
                "dir":"N"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"9",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"73",
            "uvi":"0",
            "pop":"1",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"12:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408334400",
                "month_name":"August",
                "pretty":"12:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"00",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"0",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.91"
            },
            "temp":{
                "metric":"22",
                "english":"71"
            },
            "dewpoint":{
                "metric":"17",
                "english":"63"
            },
            "feelslike":{
                "metric":"22",
                "english":"71"
            },
            "wdir":{
                "degrees":"18",
                "dir":"NNE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"10",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"75",
            "uvi":"0",
            "pop":"1",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"1:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408338000",
                "month_name":"August",
                "pretty":"1:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"01",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"1",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.9"
            },
            "temp":{
                "metric":"21",
                "english":"70"
            },
            "dewpoint":{
                "metric":"17",
                "english":"63"
            },
            "feelslike":{
                "metric":"21",
                "english":"70"
            },
            "wdir":{
                "degrees":"25",
                "dir":"NNE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"8",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"78",
            "uvi":"0",
            "pop":"1",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"2:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408341600",
                "month_name":"August",
                "pretty":"2:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"02",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"2",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1012",
                "english":"29.89"
            },
            "temp":{
                "metric":"21",
                "english":"70"
            },
            "dewpoint":{
                "metric":"17",
                "english":"63"
            },
            "feelslike":{
                "metric":"21",
                "english":"70"
            },
            "wdir":{
                "degrees":"32",
                "dir":"NNE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"9",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"80",
            "uvi":"0",
            "pop":"1",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"3:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408345200",
                "month_name":"August",
                "pretty":"3:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"03",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"3",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1012",
                "english":"29.89"
            },
            "temp":{
                "metric":"21",
                "english":"69"
            },
            "dewpoint":{
                "metric":"17",
                "english":"63"
            },
            "feelslike":{
                "metric":"21",
                "english":"69"
            },
            "wdir":{
                "degrees":"37",
                "dir":"NE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"16",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Clear",
            "humidity":"83",
            "uvi":"0",
            "pop":"1",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"4:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408348800",
                "month_name":"August",
                "pretty":"4:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"04",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"4",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1012",
                "english":"29.89"
            },
            "temp":{
                "metric":"20",
                "english":"68"
            },
            "dewpoint":{
                "metric":"17",
                "english":"63"
            },
            "feelslike":{
                "metric":"20",
                "english":"68"
            },
            "wdir":{
                "degrees":"42",
                "dir":"NE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"22",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Clear",
            "humidity":"85",
            "uvi":"0",
            "pop":"1",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"5:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408352400",
                "month_name":"August",
                "pretty":"5:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"05",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"5",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1012",
                "english":"29.89"
            },
            "temp":{
                "metric":"19",
                "english":"67"
            },
            "dewpoint":{
                "metric":"17",
                "english":"62"
            },
            "feelslike":{
                "metric":"19",
                "english":"67"
            },
            "wdir":{
                "degrees":"52",
                "dir":"NE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"20",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Clear",
            "humidity":"85",
            "uvi":"0",
            "pop":"1",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"6:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408356000",
                "month_name":"August",
                "pretty":"6:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"06",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"6",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.9"
            },
            "temp":{
                "metric":"19",
                "english":"66"
            },
            "dewpoint":{
                "metric":"17",
                "english":"62"
            },
            "feelslike":{
                "metric":"19",
                "english":"66"
            },
            "wdir":{
                "degrees":"56",
                "dir":"NE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"1",
            "sky":"24",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Sunny",
            "humidity":"87",
            "uvi":"0",
            "pop":"1",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"7:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408359600",
                "month_name":"August",
                "pretty":"7:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"07",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"7",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Clear",
            "icon":"clear"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.9"
            },
            "temp":{
                "metric":"21",
                "english":"69"
            },
            "dewpoint":{
                "metric":"16",
                "english":"61"
            },
            "feelslike":{
                "metric":"21",
                "english":"69"
            },
            "wdir":{
                "degrees":"70",
                "dir":"ENE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"32",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"78",
            "uvi":"1",
            "pop":"1",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"8:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408363200",
                "month_name":"August",
                "pretty":"8:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"08",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"8",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.91"
            },
            "temp":{
                "metric":"22",
                "english":"71"
            },
            "dewpoint":{
                "metric":"16",
                "english":"60"
            },
            "feelslike":{
                "metric":"22",
                "english":"71"
            },
            "wdir":{
                "degrees":"88",
                "dir":"E"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"49",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"69",
            "uvi":"2",
            "pop":"1",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"9:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408366800",
                "month_name":"August",
                "pretty":"9:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"09",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"9",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.91"
            },
            "temp":{
                "metric":"23",
                "english":"74"
            },
            "dewpoint":{
                "metric":"16",
                "english":"61"
            },
            "feelslike":{
                "metric":"23",
                "english":"74"
            },
            "wdir":{
                "degrees":"97",
                "dir":"E"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"58",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"62",
            "uvi":"3",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"10:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408370400",
                "month_name":"August",
                "pretty":"10:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"10",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"10",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1013",
                "english":"29.9"
            },
            "temp":{
                "metric":"25",
                "english":"77"
            },
            "dewpoint":{
                "metric":"16",
                "english":"61"
            },
            "feelslike":{
                "metric":"25",
                "english":"77"
            },
            "wdir":{
                "degrees":"112",
                "dir":"ESE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/mostlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"3",
            "sky":"65",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Cloudy",
            "humidity":"57",
            "uvi":"5",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"11:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408374000",
                "month_name":"August",
                "pretty":"11:00 AM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"11",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"11",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Mostly Cloudy",
            "icon":"mostlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1012",
                "english":"29.88"
            },
            "temp":{
                "metric":"26",
                "english":"79"
            },
            "dewpoint":{
                "metric":"16",
                "english":"61"
            },
            "feelslike":{
                "metric":"26",
                "english":"79"
            },
            "wdir":{
                "degrees":"126",
                "dir":"SE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/cloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"4",
            "sky":"80",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Cloudy",
            "humidity":"54",
            "uvi":"5",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"12:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408377600",
                "month_name":"August",
                "pretty":"12:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"12",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"12",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Overcast",
            "icon":"cloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"28",
                "english":"82"
            },
            "mslp":{
                "metric":"1011",
                "english":"29.86"
            },
            "temp":{
                "metric":"27",
                "english":"81"
            },
            "dewpoint":{
                "metric":"17",
                "english":"62"
            },
            "feelslike":{
                "metric":"28",
                "english":"82"
            },
            "wdir":{
                "degrees":"138",
                "dir":"SE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/mostlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"3",
            "sky":"74",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Cloudy",
            "humidity":"52",
            "uvi":"7",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"1:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408381200",
                "month_name":"August",
                "pretty":"1:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"13",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"13",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Mostly Cloudy",
            "icon":"mostlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"29",
                "english":"83"
            },
            "mslp":{
                "metric":"1011",
                "english":"29.84"
            },
            "temp":{
                "metric":"28",
                "english":"83"
            },
            "dewpoint":{
                "metric":"17",
                "english":"63"
            },
            "feelslike":{
                "metric":"29",
                "english":"83"
            },
            "wdir":{
                "degrees":"154",
                "dir":"SSE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/cloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"4",
            "sky":"88",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Cloudy",
            "humidity":"51",
            "uvi":"4",
            "pop":"0",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"2:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408384800",
                "month_name":"August",
                "pretty":"2:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"14",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"14",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Overcast",
            "icon":"cloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"29",
                "english":"84"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.81"
            },
            "temp":{
                "metric":"28",
                "english":"82"
            },
            "dewpoint":{
                "metric":"18",
                "english":"64"
            },
            "feelslike":{
                "metric":"29",
                "english":"84"
            },
            "wdir":{
                "degrees":"157",
                "dir":"SSE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/cloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"4",
            "sky":"80",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Cloudy",
            "humidity":"54",
            "uvi":"4",
            "pop":"2",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"3:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408388400",
                "month_name":"August",
                "pretty":"3:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"15",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"15",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Overcast",
            "icon":"cloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"29",
                "english":"84"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.79"
            },
            "temp":{
                "metric":"28",
                "english":"82"
            },
            "dewpoint":{
                "metric":"18",
                "english":"64"
            },
            "feelslike":{
                "metric":"29",
                "english":"84"
            },
            "wdir":{
                "degrees":"152",
                "dir":"SSE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/cloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"4",
            "sky":"82",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Cloudy",
            "humidity":"55",
            "uvi":"3",
            "pop":"2",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"4:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408392000",
                "month_name":"August",
                "pretty":"4:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"16",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"16",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Overcast",
            "icon":"cloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"28",
                "english":"82"
            },
            "mslp":{
                "metric":"1008",
                "english":"29.78"
            },
            "temp":{
                "metric":"27",
                "english":"81"
            },
            "dewpoint":{
                "metric":"18",
                "english":"64"
            },
            "feelslike":{
                "metric":"28",
                "english":"82"
            },
            "wdir":{
                "degrees":"146",
                "dir":"SE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/cloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"4",
            "sky":"82",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Cloudy",
            "humidity":"57",
            "uvi":"2",
            "pop":"3",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"5:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408395600",
                "month_name":"August",
                "pretty":"5:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"17",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"17",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Overcast",
            "icon":"cloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"28",
                "english":"82"
            },
            "mslp":{
                "metric":"1008",
                "english":"29.78"
            },
            "temp":{
                "metric":"27",
                "english":"81"
            },
            "dewpoint":{
                "metric":"18",
                "english":"64"
            },
            "feelslike":{
                "metric":"28",
                "english":"82"
            },
            "wdir":{
                "degrees":"136",
                "dir":"SE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/cloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"4",
            "sky":"92",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Cloudy",
            "humidity":"57",
            "uvi":"0",
            "pop":"2",
            "wspd":{
                "metric":"10",
                "english":"6"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"6:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408399200",
                "month_name":"August",
                "pretty":"6:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"18",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"18",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Overcast",
            "icon":"cloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1008",
                "english":"29.78"
            },
            "temp":{
                "metric":"26",
                "english":"79"
            },
            "dewpoint":{
                "metric":"18",
                "english":"65"
            },
            "feelslike":{
                "metric":"26",
                "english":"79"
            },
            "wdir":{
                "degrees":"132",
                "dir":"SE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/cloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"4",
            "sky":"85",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Cloudy",
            "humidity":"61",
            "uvi":"0",
            "pop":"2",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"7:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408402800",
                "month_name":"August",
                "pretty":"7:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"19",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"19",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Overcast",
            "icon":"cloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.79"
            },
            "temp":{
                "metric":"25",
                "english":"77"
            },
            "dewpoint":{
                "metric":"19",
                "english":"66"
            },
            "feelslike":{
                "metric":"25",
                "english":"77"
            },
            "wdir":{
                "degrees":"132",
                "dir":"SE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"3",
            "sky":"77",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Cloudy",
            "humidity":"68",
            "uvi":"0",
            "pop":"3",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"8:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408406400",
                "month_name":"August",
                "pretty":"8:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"20",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"20",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Mostly Cloudy",
            "icon":"mostlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.8"
            },
            "temp":{
                "metric":"24",
                "english":"75"
            },
            "dewpoint":{
                "metric":"19",
                "english":"67"
            },
            "feelslike":{
                "metric":"24",
                "english":"75"
            },
            "wdir":{
                "degrees":"137",
                "dir":"SE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"3",
            "sky":"65",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Cloudy",
            "humidity":"75",
            "uvi":"0",
            "pop":"4",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"9:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408410000",
                "month_name":"August",
                "pretty":"9:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"21",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"21",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Mostly Cloudy",
            "icon":"mostlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.8"
            },
            "temp":{
                "metric":"23",
                "english":"74"
            },
            "dewpoint":{
                "metric":"20",
                "english":"68"
            },
            "feelslike":{
                "metric":"23",
                "english":"74"
            },
            "wdir":{
                "degrees":"142",
                "dir":"SE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"3",
            "sky":"61",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Mostly Cloudy",
            "humidity":"82",
            "uvi":"0",
            "pop":"5",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"10:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408413600",
                "month_name":"August",
                "pretty":"10:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"22",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"22",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Mostly Cloudy",
            "icon":"mostlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.8"
            },
            "temp":{
                "metric":"22",
                "english":"72"
            },
            "dewpoint":{
                "metric":"20",
                "english":"68"
            },
            "feelslike":{
                "metric":"22",
                "english":"72"
            },
            "wdir":{
                "degrees":"135",
                "dir":"SE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"53",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"85",
            "uvi":"0",
            "pop":"13",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"11:00 PM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"229",
                "weekday_name_night":"Monday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"18",
                "weekday_name":"Monday",
                "epoch":"1408417200",
                "month_name":"August",
                "pretty":"11:00 PM EDT on August 18, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Monday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"23",
                "mon":"8",
                "weekday_name_unlang":"Monday",
                "mday":"18",
                "hour":"23",
                "ampm":"PM",
                "age":"",
                "weekday_name_abbrev":"Mon"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.79"
            },
            "temp":{
                "metric":"22",
                "english":"72"
            },
            "dewpoint":{
                "metric":"20",
                "english":"68"
            },
            "feelslike":{
                "metric":"22",
                "english":"72"
            },
            "wdir":{
                "degrees":"122",
                "dir":"ESE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"45",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"88",
            "uvi":"0",
            "pop":"13",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"12:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408420800",
                "month_name":"August",
                "pretty":"12:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"00",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"0",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1008",
                "english":"29.78"
            },
            "temp":{
                "metric":"22",
                "english":"71"
            },
            "dewpoint":{
                "metric":"21",
                "english":"69"
            },
            "feelslike":{
                "metric":"22",
                "english":"71"
            },
            "wdir":{
                "degrees":"100",
                "dir":"E"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"39",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"91",
            "uvi":"0",
            "pop":"9",
            "wspd":{
                "metric":"3",
                "english":"2"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"1:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408424400",
                "month_name":"August",
                "pretty":"1:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"01",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"1",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1008",
                "english":"29.77"
            },
            "temp":{
                "metric":"22",
                "english":"71"
            },
            "dewpoint":{
                "metric":"21",
                "english":"69"
            },
            "feelslike":{
                "metric":"22",
                "english":"71"
            },
            "wdir":{
                "degrees":"84",
                "dir":"E"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"40",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"91",
            "uvi":"0",
            "pop":"11",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"2:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408428000",
                "month_name":"August",
                "pretty":"2:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"02",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"2",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1007",
                "english":"29.75"
            },
            "temp":{
                "metric":"22",
                "english":"71"
            },
            "dewpoint":{
                "metric":"21",
                "english":"69"
            },
            "feelslike":{
                "metric":"22",
                "english":"71"
            },
            "wdir":{
                "degrees":"75",
                "dir":"ENE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"46",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"92",
            "uvi":"0",
            "pop":"7",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"3:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408431600",
                "month_name":"August",
                "pretty":"3:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"03",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"3",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1008",
                "english":"29.76"
            },
            "temp":{
                "metric":"22",
                "english":"71"
            },
            "dewpoint":{
                "metric":"21",
                "english":"69"
            },
            "feelslike":{
                "metric":"22",
                "english":"71"
            },
            "wdir":{
                "degrees":"68",
                "dir":"ENE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"50",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"93",
            "uvi":"0",
            "pop":"9",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"4:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408435200",
                "month_name":"August",
                "pretty":"4:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"04",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"4",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1007",
                "english":"29.75"
            },
            "temp":{
                "metric":"22",
                "english":"71"
            },
            "dewpoint":{
                "metric":"21",
                "english":"69"
            },
            "feelslike":{
                "metric":"22",
                "english":"71"
            },
            "wdir":{
                "degrees":"66",
                "dir":"ENE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"58",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"93",
            "uvi":"0",
            "pop":"11",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"5:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408438800",
                "month_name":"August",
                "pretty":"5:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"05",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"5",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1008",
                "english":"29.76"
            },
            "temp":{
                "metric":"21",
                "english":"70"
            },
            "dewpoint":{
                "metric":"21",
                "english":"69"
            },
            "feelslike":{
                "metric":"21",
                "english":"70"
            },
            "wdir":{
                "degrees":"63",
                "dir":"ENE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/nt_chancetstorms.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"14",
            "sky":"68",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Isolated Thunderstorms",
            "humidity":"94",
            "uvi":"0",
            "pop":"32",
            "wspd":{
                "metric":"5",
                "english":"3"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"6:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408442400",
                "month_name":"August",
                "pretty":"6:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"06",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"6",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Chance of a Thunderstorm",
            "icon":"chancetstorms"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1008",
                "english":"29.77"
            },
            "temp":{
                "metric":"21",
                "english":"70"
            },
            "dewpoint":{
                "metric":"21",
                "english":"69"
            },
            "feelslike":{
                "metric":"21",
                "english":"70"
            },
            "wdir":{
                "degrees":"62",
                "dir":"ENE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/chancetstorms.gif",
            "qpf":{
                "metric":"0",
                "english":"0.01"
            },
            "fctcode":"14",
            "sky":"62",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Isolated Thunderstorms",
            "humidity":"96",
            "uvi":"0",
            "pop":"33",
            "wspd":{
                "metric":"6",
                "english":"4"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"7:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408446000",
                "month_name":"August",
                "pretty":"7:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"07",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"7",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Chance of a Thunderstorm",
            "icon":"chancetstorms"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.79"
            },
            "temp":{
                "metric":"22",
                "english":"71"
            },
            "dewpoint":{
                "metric":"21",
                "english":"69"
            },
            "feelslike":{
                "metric":"22",
                "english":"71"
            },
            "wdir":{
                "degrees":"58",
                "dir":"ENE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"49",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"92",
            "uvi":"1",
            "pop":"9",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"8:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408449600",
                "month_name":"August",
                "pretty":"8:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"08",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"8",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.8"
            },
            "temp":{
                "metric":"22",
                "english":"72"
            },
            "dewpoint":{
                "metric":"20",
                "english":"68"
            },
            "feelslike":{
                "metric":"22",
                "english":"72"
            },
            "wdir":{
                "degrees":"63",
                "dir":"ENE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"48",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"86",
            "uvi":"2",
            "pop":"7",
            "wspd":{
                "metric":"8",
                "english":"5"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"9:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408453200",
                "month_name":"August",
                "pretty":"9:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"09",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"9",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        },
        {
            "windchill":{
                "metric":"-9999",
                "english":"-9999"
            },
            "heatindex":{
                "metric":"-9999",
                "english":"-9999"
            },
            "mslp":{
                "metric":"1009",
                "english":"29.81"
            },
            "temp":{
                "metric":"23",
                "english":"74"
            },
            "dewpoint":{
                "metric":"19",
                "english":"67"
            },
            "feelslike":{
                "metric":"23",
                "english":"74"
            },
            "wdir":{
                "degrees":"73",
                "dir":"ENE"
            },
            "icon_url":"http://icons.wxug.com/i/c/k/partlycloudy.gif",
            "qpf":{
                "metric":"0",
                "english":"0.0"
            },
            "fctcode":"2",
            "sky":"50",
            "snow":{
                "metric":"0",
                "english":"0.0"
            },
            "wx":"Partly Cloudy",
            "humidity":"79",
            "uvi":"3",
            "pop":"4",
            "wspd":{
                "metric":"10",
                "english":"6"
            },
            "FCTTIME":{
                "min_unpadded":"0",
                "civil":"10:00 AM",
                "mon_padded":"08",
                "sec":"0",
                "month_name_abbrev":"Aug",
                "year":"2014",
                "yday":"230",
                "weekday_name_night":"Tuesday Night",
                "isdst":"1",
                "min":"00",
                "mday_padded":"19",
                "weekday_name":"Tuesday",
                "epoch":"1408456800",
                "month_name":"August",
                "pretty":"10:00 AM EDT on August 19, 2014",
                "mon_abbrev":"Aug",
                "weekday_name_night_unlang":"Tuesday Night",
                "tz":"",
                "UTCDATE":"",
                "hour_padded":"10",
                "mon":"8",
                "weekday_name_unlang":"Tuesday",
                "mday":"19",
                "hour":"10",
                "ampm":"AM",
                "age":"",
                "weekday_name_abbrev":"Tue"
            },
            "condition":"Partly Cloudy",
            "icon":"partlycloudy"
        }
    ],
    "response":{
        "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
        "version":"0.1",
        "features":{
            "hourly":1
        }
    }
}